### ISSUE TITLE
error after typing yo miojo command.

### ISSUE THREAD

**Issue by paulo9** [Russian60/miojo#1]
events.js:72
        throw er; // Unhandled 'error' event
              ^
AssertionError: /home/user/.nvm/v0.10.40/lib/node_modules/generator-miojo/generators/app/templates/.gitignore doesn't exist
    at EditionInterface.module.exports [as read](/home/user/.nvm/v0.10.40/lib/node_modules/generator-miojo/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at template (/home/user/.nvm/v0.10.40/lib/node_modules/generator-miojo/node_modules/yeoman-generator/lib/actions/actions.js:198:34)
    at module.exports.yeoman.generators.Base.extend.writing.projectfiles (/home/user/.nvm/v0.10.40/lib/node_modules/generator-miojo/generators/app/index.js:70:12)
    at /home/user/.nvm/v0.10.40/lib/node_modules/generator-miojo/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback](timers.js:363:15)

**Comment by russiann** [comment]
Error fixed in last commit. :) https://github.com/Russian60/miojo/commit/1e32cae1e40654a9cad5ae8704804aef4fd8c9f1
